Customers.remove({});
addCustomer('Tyler', 'Sheffels')
addCustomer('Duncan', 'Renfrow')
addCustomer('Josh', 'A')
addCustomer('Tim', 'B')
addCustomer('TARK', 'MCMAINS')
addCustomer('Brendan', 'Nolan')
addCustomer('John', 'Doe')
addCustomer('Jim', 'Raynor')
addCustomer('Mike', 'Hunt')
addCustomer('James', 'Bond')
addCustomer('Sean', 'Connery')
addCustomer('Woody', 'Allen')
addCustomer('Brad', 'Pitt')
addCustomer('Jennifer', 'Aniston')
addCustomer('Angelina', 'Jolie')
addCustomer('Jenna', 'Jameson')
addCustomer('Jonnie', 'Depp')
addCustomer('Greg', 'Silverberg')
addCustomer('Clark', 'Kent')
addCustomer('Bruce', 'Wayne')
addCustomer('Bruce', 'Willis')
addCustomer('Lil', 'Wayne')


Forms.remove({});


addForm('Collar', 'Collar', 'number')
addForm('Chest', 'Chest', 'number')
addForm('Waist', 'Waist', 'number')
addForm('Front Chest', 'Front Chest', 'number')
addForm('Chest with Arms', 'Chest with Arms', 'number')
addForm('Back Chest', 'Back Chest', 'number')
addForm('Shoulders', 'Shoulders', 'number')
addForm('Half Shoulder', 'Half Shoulder', 'number')
addForm('Sleeves', 'Sleeves', 'number')
addForm('Bicep', 'Bicep', 'number')
addForm('Armpit', 'Armpit', 'number')
addForm('Front Length', 'Front Length', 'number')
addForm('Vest Length', 'Vest Length', 'number')
addForm('Waist', 'Waist', 'number')
addForm('Hips', 'Hips', 'number')
addForm('Length', 'Length', 'number')
addForm('Thigh', 'Thigh', 'number')
addForm('Knee', 'Knee', 'number')
addForm('Calf', 'Calf', 'number')
addForm('Bottom', 'Bottom', 'number')
addForm('U Rise', 'U Rise', 'number')
addForm('Front Rise', 'Front Rise', 'number')
addForm('Inseam', 'Inseam', 'number')